### ISSUE TITLE
Several scenes in this directory still need to be either updated or deleted (out of date). 

### ISSUE THREAD

**Issue by tlian7** [scienstanford/RTBscenes#1]
I will fix this issue sometime this week, but I just wanted to make everyone aware of this. The scripts that are working are the ones that were updated within a month ago.

**Comment by wandell** [comment]
Thanks for the comment/issue.  We saw this yesterday.  But a few worked well.

I made some very small edits to help the failure cases (catching the error and printing at that point rather than waiting for a crash).  I also edited some of the scripts to return the user to the original directory at the end.  

Mostly, looks great.  We (mainly Henryk) are starting to interact a little more with Ben.  I am sure you are involved as well ... though I am having a hard time keeping up with who is doing what.  

Hope you are well in Seattle!
